name: docs

on:
  push:
    branches: [ master ]
    paths: [ '**.java' ]

jobs:
  api-website:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 1.11

    - run: chmod +x gradlew
    - run: ./gradlew javadoc

    - name: Tidy up the javadocs
      id: tidy
      uses: cicirello/javadoc-cleanup@v1.2.0
      with:
        path-to-root: docs
    
    - name: Log javadoc-cleanup output
      run: |
        echo "modified-count = ${{ steps.tidy.outputs.modified-count }}"
    
    - name: Commit documentation changes
      run: |
        if [ $(git status | grep -c "**/*.html") == "0" ]; then
          git checkout .
        else
          git config --global user.name 'Titan Robotics'
          git config --global user.email 'noreply@frc5431.com'
          git add -A
          git commit -m "Automated API website updates."
        fi
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3.4.0
      with:
        title: "Automated API website updates."
        commit-message: "Automated API documentation website updates."